import { test, expect } from "@playwright/test";

test.describe("Notice Management Flow", () => {
  test("should create, display, and delete a notice", async ({ page }) => {
    // 1. Open the page
    await page.goto("/");
    
    // Check if the empty state or grid is visible
    await expect(page.getByRole("heading", { name: "Notice Board" })).toBeVisible();

    // 2. Create a notice
    // Click the "Create Notice" button
    await page.click('button:has-text("Create Notice")');
    
    // Ensure the dialog opens
    await expect(page.getByRole("heading", { name: "Create Notice" })).toBeVisible();

    // Fill in the form
    const uniqueTitle = `Test Notice ${Date.now()}`;
    await page.fill('input[id="notice-title"]', uniqueTitle);
    await page.fill('textarea[id="notice-body"]', "This is a test notice body generated by Playwright.");
    
    // Select category and priority
    await page.selectOption('select[id="notice-category"]', "GENERAL");
    await page.selectOption('select[id="notice-priority"]', "NORMAL");
    
    // Submit the form
    await page.click('button:has-text("Publish Notice")');

    // Verify toast notification (Sonner)
    await expect(page.getByText("Notice published successfully")).toBeVisible();

    // 3. Verify the notice appears in the list
    const noticeCard = page.locator(".group.relative", { hasText: uniqueTitle });
    await expect(noticeCard).toBeVisible();

    // 4. Delete the notice
    // Hover to reveal action buttons
    await noticeCard.hover();
    
    // Click delete
    await noticeCard.locator('button[aria-label^="Delete notice"]').click();

    // Ensure the confirmation dialog opens
    await expect(page.getByRole("heading", { name: "Delete Notice" })).toBeVisible();

    // Confirm deletion
    await page.click('button:has-text("Delete Notice")');

    // Verify toast notification
    await expect(page.getByText("Notice deleted successfully")).toBeVisible();

    // Ensure the notice is removed from the list
    await expect(noticeCard).not.toBeVisible();
  });
});
